In [106]:
import pandas as pd

In [107]:
df_goals = pd.read_csv('goals.csv')
df_goals.head()

,key_id,goal_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,...,shirt_number,player_team_id,player_team_name,player_team_code,minute_label,minute_regulation,minute_stoppage,match_period,own_goal,penalty
0,1,G-0001,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,T-30,...,0,T-30,France,FRA,19',19,0,first half,0,0
1,2,G-0002,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,T-30,...,0,T-30,France,FRA,40',40,0,first half,0,0
2,3,G-0003,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,T-30,...,0,T-30,France,FRA,43',43,0,first half,0,0
3,4,G-0004,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,T-46,...,0,T-46,Mexico,MEX,70',70,0,second half,0,0
4,5,G-0005,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,1930-07-13,group stage,Group 1,T-30,...,0,T-30,France,FRA,87',87,0,second half,0,0

In [108]:
df_goals.dtypes

key_id                int64
goal_id              object
tournament_id        object
tournament_name      object
match_id             object
match_name           object
match_date           object
stage_name           object
group_name           object
team_id              object
team_name            object
team_code            object
home_team             int64
away_team             int64
player_id            object
family_name          object
given_name           object
shirt_number          int64
player_team_id       object
player_team_name     object
player_team_code     object
minute_label         object
minute_regulation     int64
minute_stoppage       int64
match_period         object
own_goal              int64
penalty               int64
dtype: object

In [109]:
df_goals.columns.tolist()

['key_id',
 'goal_id',
 'tournament_id',
 'tournament_name',
 'match_id',
 'match_name',
 'match_date',
 'stage_name',
 'group_name',
 'team_id',
 'team_name',
 'team_code',
 'home_team',
 'away_team',
 'player_id',
 'family_name',
 'given_name',
 'shirt_number',
 'player_team_id',
 'player_team_name',
 'player_team_code',
 'minute_label',
 'minute_regulation',
 'minute_stoppage',
 'match_period',
 'own_goal',
 'penalty']

In [110]:
df_matches = pd.read_csv('matches.csv')
df_matches.head()

,key_id,tournament_id,tournament_name,match_id,match_name,stage_name,group_name,group_stage,knockout_stage,replayed,...,away_team_score_margin,extra_time,penalty_shootout,score_penalties,home_team_score_penalties,away_team_score_penalties,result,home_team_win,away_team_win,draw
0,1,WC-1930,1930 FIFA Men's World Cup,M-1930-01,France vs Mexico,group stage,Group 1,1,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0
1,2,WC-1930,1930 FIFA Men's World Cup,M-1930-02,United States vs Belgium,group stage,Group 4,1,0,0,...,-3,0,0,0-0,0,0,home team win,1,0,0
2,3,WC-1930,1930 FIFA Men's World Cup,M-1930-03,Yugoslavia vs Brazil,group stage,Group 2,1,0,0,...,-1,0,0,0-0,0,0,home team win,1,0,0
3,4,WC-1930,1930 FIFA Men's World Cup,M-1930-04,Romania vs Peru,group stage,Group 3,1,0,0,...,-2,0,0,0-0,0,0,home team win,1,0,0
4,5,WC-1930,1930 FIFA Men's World Cup,M-1930-05,Argentina vs France,group stage,Group 1,1,0,0,...,-1,0,0,0-0,0,0,home team win,1,0,0

In [111]:
df_matches.columns.tolist()

['key_id',
 'tournament_id',
 'tournament_name',
 'match_id',
 'match_name',
 'stage_name',
 'group_name',
 'group_stage',
 'knockout_stage',
 'replayed',
 'replay',
 'match_date',
 'match_time',
 'stadium_id',
 'stadium_name',
 'city_name',
 'country_name',
 'home_team_id',
 'home_team_name',
 'home_team_code',
 'away_team_id',
 'away_team_name',
 'away_team_code',
 'score',
 'home_team_score',
 'away_team_score',
 'home_team_score_margin',
 'away_team_score_margin',
 'extra_time',
 'penalty_shootout',
 'score_penalties',
 'home_team_score_penalties',
 'away_team_score_penalties',
 'result',
 'home_team_win',
 'away_team_win',
 'draw']

In [112]:
df_player_appearances = pd.read_csv('player_appearances.csv')
df_player_appearances.head()

,key_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,team_name,...,home_team,away_team,player_id,family_name,given_name,shirt_number,position_name,position_code,starter,substitute
0,1,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,Mexico,...,1,0,P-66980,Calderón,Ignacio,1,goal keeper,GK,1,0
1,2,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,Mexico,...,1,0,P-64553,Peña,Gustavo,3,defender,DF,1,0
2,3,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,Mexico,...,1,0,P-42664,Pérez,Mario,5,defender,DF,1,0
3,4,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,Mexico,...,1,0,P-69898,Hernández,Guillermo,6,midfielder,MF,1,0
4,5,WC-1970,1970 FIFA Men's World Cup,M-1970-01,Mexico vs Soviet Union,1970-05-31,group stage,Group 1,T-46,Mexico,...,1,0,P-56971,Salgado,Horacio López,10,forward,FW,1,0

Como é possível notar a tabela Player Appearances, se inicia com dados a partir de 1970, por isso devemos trazer os dados para se iniciar a partir deste mesmo ano.

In [113]:
df_matches = df_matches[df_matches['match_date'] >= "1970-01-01"]
df_goals = df_goals[df_goals['match_date'] >= "1970-01-01"]

Precisamos definir o ano de cada partida, para isso vamos criar a coluna YEAR

In [114]:
df_goals ['match_date']= pd.to_datetime(df_goals['match_date'])
df_goals['year'] = df_goals['match_date'].dt.year
df_goals[['year', 'match_date']].head()

df_player_appearances ['match_date']= pd.to_datetime(df_player_appearances['match_date'])
df_player_appearances['year'] = df_player_appearances['match_date'].dt.year
df_player_appearances[['year', 'match_date']].head()

   year match_date
0  1970 1970-05-31
1  1970 1970-05-31
2  1970 1970-05-31
3  1970 1970-05-31
4  1970 1970-05-31

In [115]:
df_goals = df_goals.groupby(['team_id', 'year', 'player_id']).size().reset_index(name='total_goals')
df_goals.head()

  team_id  year player_id  total_goals
0    T-01  1982   P-40338            2
1    T-01  1982   P-45774            1
2    T-01  1982   P-59774            1
3    T-01  1982   P-68346            1
4    T-01  1986   P-42885            1

In [116]:
idx = df_goals.groupby(['team_id', 'year'])['total_goals'].idxmax()
estrelas = df_goals.loc[idx]
estrelas.head()

   team_id  year player_id  total_goals
0     T-01  1982   P-40338            2
4     T-01  1986   P-42885            1
8     T-01  2014   P-59147            2
10    T-02  2006   P-78483            1
11    T-03  1974   P-04739            3

In [117]:
estrela_play = estrelas.merge(df_player_appearances, on=['team_id', 'year', 'player_id'], how='left')
estrela_play.head()

,team_id,year,player_id,total_goals,key_id,tournament_id,tournament_name,match_id,match_name,match_date,...,team_code,home_team,away_team,family_name,given_name,shirt_number,position_name,position_code,starter,substitute
0,T-01,1982,P-40338,2,2862.0,WC-1982,1982 FIFA Men's World Cup,M-1982-07,West Germany vs Algeria,1982-06-16,...,DZA,0.0,1.0,Assad,Salah,7.0,forward,FW,1.0,0.0
1,T-01,1982,P-40338,2,3223.0,WC-1982,1982 FIFA Men's World Cup,M-1982-22,Algeria vs Austria,1982-06-21,...,DZA,1.0,0.0,Assad,Salah,7.0,forward,FW,1.0,0.0
2,T-01,1982,P-40338,2,3451.0,WC-1982,1982 FIFA Men's World Cup,M-1982-31,Algeria vs Chile,1982-06-24,...,DZA,1.0,0.0,Assad,Salah,7.0,forward,FW,1.0,0.0
3,T-01,1986,P-42885,1,4191.0,WC-1986,1986 FIFA Men's World Cup,M-1986-08,Algeria vs Northern Ireland,1986-06-03,...,DZA,1.0,0.0,Zidane,Djamel,14.0,midfielder,MF,1.0,0.0
4,T-01,1986,P-42885,1,4442.0,WC-1986,1986 FIFA Men's World Cup,M-1986-17,Brazil vs Algeria,1986-06-06,...,DZA,0.0,1.0,Zidane,Djamel,14.0,midfielder,MF,0.0,1.0

In [118]:
estrela_play.columns.tolist()

['team_id',
 'year',
 'player_id',
 'total_goals',
 'key_id',
 'tournament_id',
 'tournament_name',
 'match_id',
 'match_name',
 'match_date',
 'stage_name',
 'group_name',
 'team_name',
 'team_code',
 'home_team',
 'away_team',
 'family_name',
 'given_name',
 'shirt_number',
 'position_name',
 'position_code',
 'starter',
 'substitute']

In [119]:
df_estrela_win = estrela_play.merge(df_matches[['match_id', 'home_team_id','away_team_id', 'home_team_win', 'away_team_win', 'draw']], on=['match_id'], how='left')
df_estrela_win.head()

,team_id,year,player_id,total_goals,key_id,tournament_id,tournament_name,match_id,match_name,match_date,...,shirt_number,position_name,position_code,starter,substitute,home_team_id,away_team_id,home_team_win,away_team_win,draw
0,T-01,1982,P-40338,2,2862.0,WC-1982,1982 FIFA Men's World Cup,M-1982-07,West Germany vs Algeria,1982-06-16,...,7.0,forward,FW,1.0,0.0,T-86,T-01,0.0,1.0,0.0
1,T-01,1982,P-40338,2,3223.0,WC-1982,1982 FIFA Men's World Cup,M-1982-22,Algeria vs Austria,1982-06-21,...,7.0,forward,FW,1.0,0.0,T-01,T-05,0.0,1.0,0.0
2,T-01,1982,P-40338,2,3451.0,WC-1982,1982 FIFA Men's World Cup,M-1982-31,Algeria vs Chile,1982-06-24,...,7.0,forward,FW,1.0,0.0,T-01,T-13,1.0,0.0,0.0
3,T-01,1986,P-42885,1,4191.0,WC-1986,1986 FIFA Men's World Cup,M-1986-08,Algeria vs Northern Ireland,1986-06-03,...,14.0,midfielder,MF,1.0,0.0,T-01,T-52,0.0,0.0,1.0
4,T-01,1986,P-42885,1,4442.0,WC-1986,1986 FIFA Men's World Cup,M-1986-17,Brazil vs Algeria,1986-06-06,...,14.0,midfielder,MF,0.0,1.0,T-09,T-01,1.0,0.0,0.0

In [120]:
df_estrela_win['ganhou'] = (df_estrela_win['team_id'] == df_estrela_win['home_team_id']) & (df_estrela_win['home_team_win'] == 1) | (df_estrela_win['team_id'] == df_estrela_win['away_team_id']) & (df_estrela_win['away_team_win'] == 1)

In [121]:
df_estrela_win['ganhou'].value_counts()

ganhou
False    1052
True      803
Name: count, dtype: int64

In [122]:
# time da casa
home = df_matches[['match_id', 'home_team_id']].rename(columns={'home_team_id': 'team_id'})
  

# time visitante
away = df_matches[['match_id', 'away_team_id']].rename(columns={'away_team_id': 'team_id'})
  

# combinando os dois dataframes, cada jogo virou duas linhas por time
matches_teams = pd.concat([home, away], ignore_index=True)

matches_teams.head()

    match_id team_id
0  M-1970-01    T-46
1  M-1970-02    T-84
2  M-1970-03    T-28
3  M-1970-04    T-56
4  M-1970-05    T-06

In [123]:
# Merge com indicator

df_todos = matches_teams.merge(estrela_play[['match_id', 'team_id']],
on=['match_id', 'team_id'],
how='left',
indicator=True)
# Filtra só os que não estão no estrela_play
df_sem_estrela = df_todos[df_todos['_merge'] == 'left_only']

In [124]:
df_sem_estrela.head()

     match_id team_id     _merge
35  M-1974-04    T-88  left_only
40  M-1974-09    T-04  left_only
44  M-1974-13    T-10  left_only
48  M-1974-17    T-04  left_only
50  M-1974-19    T-88  left_only

In [125]:
# 1. Faz o merge com o df_matches para trazer de volta as colunas de validação do resultado
df_sem_estrela = df_sem_estrela.drop(columns=['home_team_id', 'away_team_id', 'home_team_win', 'away_team_win', 'draw'], errors='ignore') # Garante que não haverá duplicados se rodar mais de uma vez
df_sem_estrela = df_sem_estrela.merge(
    df_matches[['match_id', 'home_team_id', 'away_team_id', 'home_team_win', 'away_team_win', 'draw']], 
    on='match_id', 
    how='left'
)

# 2. Executa a lógica de checagem com os parênteses ajustados isolando cada cenário (Mandante e Visitante)
df_sem_estrela['ganhou'] = (
    (df_sem_estrela['team_id'] == df_sem_estrela['home_team_id']) & (df_sem_estrela['home_team_win'] == 1)
) | (
    (df_sem_estrela['team_id'] == df_sem_estrela['away_team_id']) & (df_sem_estrela['away_team_win'] == 1)
)

In [126]:
df_sem_estrela['ganhou'].value_counts()

ganhou
False    201
True      64
Name: count, dtype: int64

In [127]:
win_rate_estrela = df_estrela_win.groupby('team_id')['ganhou'].mean().reset_index(name='win_rate_estrela')

In [128]:
win_rate_sem_estrela = df_sem_estrela.groupby('team_id')['ganhou'].mean().reset_index(name='win_rate_sem_estrela')
win_rate_sem_estrela.head()

  team_id  win_rate_sem_estrela
0    T-01                  0.00
1    T-02                  0.00
2    T-03                  0.25
3    T-04                  0.25
4    T-06                  0.60

In [129]:
dependencia = win_rate_estrela.merge(win_rate_sem_estrela, on='team_id', how='inner')
dependencia['indice'] = dependencia['win_rate_estrela'] - dependencia['win_rate_sem_estrela']
dependencia.head()

  team_id  win_rate_estrela  win_rate_sem_estrela    indice
0    T-01          0.333333                  0.00  0.333333
1    T-02          0.000000                  0.00  0.000000
2    T-03          0.571429                  0.25  0.321429
3    T-04          0.222222                  0.25 -0.027778
4    T-06          0.475000                  0.60 -0.125000

In [130]:
dependencia.sort_values('indice', ascending=False).head(10)

   team_id  win_rate_estrela  win_rate_sem_estrela    indice
22    T-31          0.714286                   0.2  0.514286
39    T-57          0.485714                   0.0  0.485714
11    T-16          0.476190                   0.0  0.476190
49    T-72          0.466667                   0.0  0.466667
55    T-84          0.437500                   0.0  0.437500
52    T-75          0.400000                   0.0  0.400000
15    T-22          0.352941                   0.0  0.352941
17    T-25          0.333333                   0.0  0.333333
0     T-01          0.333333                   0.0  0.333333
12    T-17          0.333333                   0.0  0.333333

In [131]:
time_nomes = df_matches[['home_team_id', 'home_team_name']].drop_duplicates()
time_nomes.columns = ['team_id', 'team_name']
dependencia = dependencia.merge(time_nomes, how='left')
dependencia.sort_values('indice', ascending=False).head(10)

   team_id  win_rate_estrela  win_rate_sem_estrela    indice     team_name
22    T-31          0.714286                   0.2  0.514286       Germany
39    T-57          0.485714                   0.0  0.485714        Poland
11    T-16          0.476190                   0.0  0.476190      Colombia
49    T-72          0.466667                   0.0  0.466667  Soviet Union
55    T-84          0.437500                   0.0  0.437500       Uruguay
52    T-75          0.400000                   0.0  0.400000   Switzerland
15    T-22          0.352941                   0.0  0.352941       Denmark
17    T-25          0.333333                   0.0  0.333333       Ecuador
0     T-01          0.333333                   0.0  0.333333       Algeria
12    T-17          0.333333                   0.0  0.333333    Costa Rica

## Comparativo Messi vs CR7 vs Neymar

In [132]:
df_player_appearances['given_name'] = df_player_appearances['given_name'].replace('not applicable', '')
df_player_appearances['player_name'] = df_player_appearances['given_name'] + ' ' + df_player_appearances['family_name']
df_player_appearances['player_name'] = df_player_appearances['player_name'].str.strip()

In [133]:
nomes = {'Neymar', 'Lionel Messi', 'Cristiano Ronaldo'}

In [134]:
estrelas_modernas = df_player_appearances[df_player_appearances['player_name'].isin(nomes)]
estrelas_modernas.value_counts('player_name')

player_name
Lionel Messi         26
Cristiano Ronaldo    22
Neymar               13
Name: count, dtype: int64

In [135]:
estrelas_modernas = estrelas_modernas.merge(df_matches[['match_id', 'home_team_id','away_team_id', 'home_team_win', 'away_team_win', 'draw']], on=['match_id'], how='left')
estrelas_modernas['ganhou'] = (estrelas_modernas['team_id'] == estrelas_modernas['home_team_id']) & (estrelas_modernas['home_team_win'] == 1) | (estrelas_modernas['team_id'] == estrelas_modernas['away_team_id']) & (estrelas_modernas['away_team_win'] == 1)
estrelas_modernas['ganhou'].value_counts()

ganhou
True     38
False    23
Name: count, dtype: int64

In [136]:
estrelas_modernas.head()

,key_id,tournament_id,tournament_name,match_id,match_name,match_date,stage_name,group_name,team_id,team_name,...,starter,substitute,year,player_name,home_team_id,away_team_id,home_team_win,away_team_win,draw,ganhou
0,13951,WC-2006,2006 FIFA Men's World Cup,M-2006-08,Angola vs Portugal,2006-06-11,group stage,Group D,T-58,Portugal,...,1,0,2006,Cristiano Ronaldo,T-02,T-58,0,1,0,True
1,14300,WC-2006,2006 FIFA Men's World Cup,M-2006-21,Argentina vs Serbia and Montenegro,2006-06-16,group stage,Group C,T-03,Argentina,...,0,1,2006,Lionel Messi,T-03,T-67,1,0,0,True
2,14379,WC-2006,2006 FIFA Men's World Cup,M-2006-24,Portugal vs Iran,2006-06-17,group stage,Group D,T-58,Portugal,...,1,0,2006,Cristiano Ronaldo,T-58,T-38,1,0,0,True
3,14839,WC-2006,2006 FIFA Men's World Cup,M-2006-40,Netherlands vs Argentina,2006-06-21,group stage,Group C,T-03,Argentina,...,1,0,2006,Lionel Messi,T-48,T-03,0,0,1,False
4,15107,WC-2006,2006 FIFA Men's World Cup,M-2006-50,Argentina vs Mexico,2006-06-24,round of 16,not applicable,T-03,Argentina,...,0,1,2006,Lionel Messi,T-03,T-46,1,0,0,True

In [137]:
win_rate_estrelas_modernas = estrelas_modernas.groupby('player_name')['ganhou'].mean().reset_index(name='win_rate')

In [138]:
estrelas_modernas['ganhou'].value_counts()

ganhou
True     38
False    23
Name: count, dtype: int64

In [139]:
df_matches[df_matches['home_team_name'].isin(['Brazil', 'Argentina', 'Portugal'])][['home_team_name', 'home_team_id']].drop_duplicates()

    home_team_name home_team_id
206         Brazil         T-09
246      Argentina         T-03
368       Portugal         T-58

In [140]:
selecao_estrelas = {'T-09', 'T-03', 'T-58'}

df_selecoes = matches_teams[matches_teams['team_id'].isin(selecao_estrelas)]
df_selecoes.value_counts('team_id')

team_id
T-09    116
T-03     81
T-58     29
Name: count, dtype: int64

In [141]:
df_matches['match_date'] = pd.to_datetime(df_matches['match_date'])
df_matches['year'] = df_matches['match_date'].dt.year

In [142]:
# 1. Descobrir os anos em que cada jogador esteve presente em Copas do Mundo usando as estrelas modernas
anos_por_jogador = (
    estrelas_modernas.groupby(["player_id", "player_name"])["year"]
    .unique()
    .reset_index()
)

# 2. Replicar a base de jogos da seleção para CADA jogador correspondente usando o team_id
mapa_times = estrelas_modernas[
    ["player_id", "player_name", "team_id"]
].drop_duplicates()
base_periodo_jogador = mapa_times.merge(
    anos_por_jogador, on=["player_id", "player_name"]
)

# Explodir a lista de anos em linhas individuais para permitir o filtro por ano/time
base_periodo_jogador = base_periodo_jogador.explode("year")
base_periodo_jogador["year"] = base_periodo_jogador["year"].astype(int)

# CORREÇÃO DO KEYERROR: Como df_selecoes só tem match_id e team_id, trazemos o ano do df_matches
df_selecoes_ano = df_selecoes.merge(df_matches[["match_id", "match_date"]], on="match_id", how="left")
df_selecoes_ano["year"] = pd.to_datetime(df_selecoes_ano["match_date"]).dt.year

# 3. Trazer todos os jogos da seleção que aconteceram APENAS nos anos de Copa de cada jogador
jogos_no_periodo = df_selecoes_ano.merge(
    base_periodo_jogador, on=["team_id", "year"], how="inner"
)

jogos_no_periodo.head()

    match_id team_id match_date  year player_id        player_name
0  M-2006-05    T-03 2006-06-10  2006   P-14758       Lionel Messi
1  M-2006-21    T-03 2006-06-16  2006   P-14758       Lionel Messi
2  M-2006-24    T-58 2006-06-17  2006   P-70442  Cristiano Ronaldo
3  M-2006-38    T-58 2006-06-21  2006   P-70442  Cristiano Ronaldo
4  M-2006-50    T-03 2006-06-24  2006   P-14758       Lionel Messi

In [143]:
# 4. Remover os jogos em que a estrela de fato entrou em campo (usando match_id e player_id)
df_todos_periodo = jogos_no_periodo.merge(
    estrelas_modernas[["match_id", "player_id"]],
    on=["match_id", "player_id"],
    how="left",
    indicator=True,
)

# Filtrar apenas as linhas onde o jogador NÃO atuou no período dele
sem_mordernas = df_todos_periodo[
    df_todos_periodo["_merge"] == "left_only"
].copy()
sem_mordernas = sem_mordernas.drop(columns=["_merge"])

# 5. Trazer o resultado do jogo (colunas de vitória) do df_matches
sem_mordernas = sem_mordernas.merge(
    df_matches[
        [
            "match_id",
            "home_team_id",
            "away_team_id",
            "home_team_win",
            "away_team_win",
        ]
    ],
    on="match_id",
    how="left",
)

# Aplica a lógica isolando os blocos (Mandante) | (Visitante) com parênteses
sem_mordernas["ganhou"] = (
    (sem_mordernas["team_id"] == sem_mordernas["home_team_id"])
    & (sem_mordernas["home_team_win"] == 1)
) | (
    (sem_mordernas["team_id"] == sem_mordernas["away_team_id"])
    & (sem_mordernas["away_team_win"] == 1)
)

# Verificação da contagem de jogos sem as estrelas no período delas
sem_mordernas["ganhou"].value_counts()

ganhou
False    4
True     3
Name: count, dtype: int64

In [144]:
# 1. Taxa de vitória de cada jogador COM ele em campo
win_rate_estrelas_modernas = (
    estrelas_modernas.groupby("player_name")["ganhou"]
    .mean()
    .reset_index(name="win_rate")
)

# 2. Taxa de vitória da seleção SEM eles no período correto de cada um
win_rate_sem_modernas = (
    sem_mordernas.groupby("player_name")["ganhou"]
    .mean()
    .reset_index(name="win_rate_sem_modernas")
)

# 3. Junta os dados de vitória COM e SEM o jogador
dependencia_morderna = win_rate_estrelas_modernas.merge(
    win_rate_sem_modernas, on="player_name", how="inner"
)

# 4. Calcula o índice de impacto real (Dependência) de cada craque
dependencia_morderna["indice"] = (
    dependencia_morderna["win_rate"]
    - dependencia_morderna["win_rate_sem_modernas"]
)

# Exibe o resultado final estruturado por jogador
dependencia_morderna[
    ["player_name", "win_rate", "win_rate_sem_modernas", "indice"]
]

         player_name  win_rate  win_rate_sem_modernas    indice
0  Cristiano Ronaldo  0.454545                   1.00 -0.545455
1       Lionel Messi  0.730769                   0.50  0.230769
2             Neymar  0.692308                   0.25  0.442308